### PR TITLE
make ESP_IDF compatible

### PR DESCRIPTION
**Pull request by RobTillaart**

### CODE REVIEW

**Comment by RobTillaart** [comment]
@shaneapowell 

I merged your code and made some additional edits
- all bools ==> boolean  (better imho than the #define)
- fix tan(90) error 
- renamed internal variables and tables for readability
- minor edits
- bumped version to 0.2.0 

If you have time could you give it a try? (if not just let me know)

**Comment by RobTillaart** [comment]
There are some red flags in the build :(

**Comment by RobTillaart** [comment]
mmm, seems I broke a lot....

**Comment by RobTillaart** [comment]
@shaneapowell 
- Reverted bool - boolean
- added stdbool.h and stdint.h to fix build, also local ESP32 in Arduino IDE
- 
Can you verify develop branch works for you ?
Thanks

**Comment by shaneapowell** [comment]
I tried to pull your develop branch this morning to see if it works on my project.
However, I'm not able to see your develop branch.
I assume it must be protected or something?

Cheers
Shane

------------------------------ Objects in mirror are losing.
________________________________

**Comment by shaneapowell** [comment]
@RobTillaart  I tried just now, your `master` branch seems to work perfectly now with my ESP32-IDF project.
Appreciate the help making it trivial to use your work in my project.

**Comment by RobTillaart** [comment]
> I tried to pull your develop branch this morning to see if it works on my project.

Apparently I merged it before you could test it. I had tested it with ESP32 under the Arduino IDE and that failed in first attempt. Assuming the ESP_IDF define was set I added two includes and it compiled again. So I assumed that it would work for you toom so I merged and went on with other issues/ other libs. 

Good to hear it works for you, as there are some breaking changes (names of the tables) I bumped the version to 0.2.0.

One question: is the table accurate enough?
Still on my (local) todo list (low prio) is to write a python script or so to find the optimal values for the table. 
Problem is how to define optimal. Now the values for the whole degrees are as close as possible. 
That means all interpolated values are a (tiny) bit too small. 
An other definition of optimal would be that the maximum error is as small as possible including interpolated values.
If I would alternate the table-points around the sin curve the average /absolute error will be reduced. 
Drawback is that the whole degree points would have the largest error.

> Appreciate the help making it trivial to use your work in my project.

You're welcome!

**Comment by shaneapowell** [comment]
The table is accurate enough for my purposes so far.  
I'm building a POV clock (my 3rd generation). I'm using your quick trig functions to do simple Cartesian to Polar back and forth calculations based on the angle of the led arm.  Your code is move than accurate enough to handle my needs.  I was originally just using a hard-coded 90x32 lookup matrix that I generated.  But, my new POV clock is using more than 32 leds, so that old matrix is no go any more.  Hence, your Trig code is saving me re-generating that matrix, and only costing me few of extra microseconds (according to my oscillosope).

**Comment by RobTillaart** [comment]
> I'm building a POV clock (my 3rd generation).

When it works a picture would be great!

> Cartesian to Polar

Does that include degrees2radians or vice versa?
I might be interesting to investigate a sin() lookup that would be in radians, think of 
```cpp
value = rsin(radians);
```

**Comment by RobTillaart** [comment]
Are you using **atan2()** for the cartesian to polar?
Today I derived some code that is accurate to 0.001 
UNO atan2() = 196 us
UNO atan2A() = 116 us
ESP atan2() = 76 us
ESP atan2A = 17 us

It will be added to this library somewhere this week.

(It will also include atanA() which is used by atan2A() - is also faster but I forgot to write down the numbers :)

**Comment by RobTillaart** [comment]
UNO atan() = 188 us
UNO atanA() = 84 us
ESP atan() = 56 us
ESP atanA() = 11 us

**Comment by shaneapowell** [comment]
@RobTillaart 
As a matter of fact, yes. I am using atan2().  (and aslo sqrt()).
I'm using the one included within the espidf framework. It's included in the <math.h> file.
I didn't measure any real difference in performance between using the built in atan2() , and a "lookup" table that I tried as a performance test.    If you include an atan2 into your code, I'll happily give it a try, and attempt to measure any performance difference.

The only other thing that is quite different from my use of your functions, and your code is that I use all uint32_t values.
To avoid any float based math (multiply, divide, etc) I have all my values converted into fixed-floating-point values (long ints).  It's only a minor inconfience that I have to "cast" my values into a float when I call your functions.    It'd be "handy" if you happened to have uint32 and int32 variations of your functions. But.. honestly, not a big deal to cast to float too.

**Comment by RobTillaart** [comment]
created a develop branch, so you can start testing.
need to update docs / code a bit more later today.

**Comment by RobTillaart** [comment]
There is a typo in the code, will be fixed in >2hrs

----

I'm online again fixing code first
Stable enough for version 0.2.1

**Comment by RobTillaart** [comment]
@shaneapowell 
Merged the ATAN2 code ==> version 0.2.1

**Comment by RobTillaart** [comment]
@shaneapowell 

> It'd be "handy" if you happened to have uint32 and int32 variations of your functions. But.. honestly, not a big deal to cast to float too.

Can you give a minimal example how you see this?

``` sin(uint32_t val)``` ?  where is the decimal point?

**Comment by shanepowell-ast** [comment]
That's just it. My use case is not using any decimal values. All while numbers. I'm casting uint32 values into a float, and passing that into your code. Then, I cast the response back to an int. I don't even know if there is any sort of performance gain to be had with your library having an int only mode.  The part in my code that uses sin and cos is not in the led output anyway, it's all in the 10fps pre rendering side.

Eg if how I'm calling your code.

int i = (int)icos((float)r);

**Comment by RobTillaart** [comment]
```int i = (int)icos((float)r);```

ok, so your input are whole degrees.   The explicit casting  ```(float)r``` will be done automatically, so is not needed.

However casting the output of icos() will always return -1, 0 or 1 . See test
```cpp
#include "Arduino.h"
#include "FastTrig.h"

void setup()
{
  Serial.begin(115200);
  while (!Serial);
  Serial.println(__FILE__);
  delay(10);

  for (int r = 0; r < 10000; r++)
  {
    int x = (int)icos((float)r);
    Serial.println(x);
  }
}

void loop()
{
}
```

**Comment by shaneapowell** [comment]
well.. yep.. you're 100% correct.  Been a long time since I've done Trig. 
I looked in my code to figure out why it was working perfectly, despite the obvious fact that cos() must return a float.
It's because I'm running a multiplication on the output right before the final forced cast.   The math runs on the float operation correctly, then casts to the final int.  Hence, it works perfectly.  
`uin32_t cx = pixel * icos((float)step);`
I'd say you can safely ignore my (uint32_t) request.  :)

**Comment by RobTillaart** [comment]
> uin32_t cx = pixel * icos((float)step);

I expected something like that.  👍

As you are working with whole degrees one could create a **icos256()** that does the lookup and modulo math without any float. **icos256()** would return -256..256 so the code would be ```(pixel * icos256(step) ) >> 8;```
Could be faster

I will give it a try as it is interesting to know.
(I'll be back)

**Comment by RobTillaart** [comment]
add .h
```cpp
///////////////////////////////////////////////////////
//
// GONIO INT EXPERIMENTAL
//
int isin256(uint32_t v);
int icos256(uint32_t v);
```

add .cpp
```cpp
///////////////////////////////////////////////////////
//
// GONIO INT EXPERIMENTAL
//
int isin256(uint32_t v)
{
  bool negative = false;

  long whole = v;

  if (whole >= 360) whole %= 360;

  int y = whole;  //  16 bit math is faster than 32 bit

  if (y >= 180)
  {
    y -= 180;
    negative = true;
  }

  if (y >= 90)
  {
    y = 180 - y;
  }

  //  float value  improves ~4% on avg error  for ~60 bytes.
  uint16_t value = sinTable16[y];

  uint16_t g = value >> 8;
  if (negative) return -g;
  return g;
}

int icos256(uint32_t v)
{
  return isin256(v + 90);
}
```

Test sketch
```cpp
//    FILE: test_experiments.ino
//  AUTHOR: Rob Tillaart
//    DATE: 2022-12-09
// PURPOSE: R&D

#include "Arduino.h"
#include "FastTrig.h"

uint32_t start, stop;
volatile float x;
volatile int y;

void setup()
{
  Serial.begin(115200);
  while (!Serial);
  Serial.println(__FILE__);
  delay(10);

  start = micros();
  for (uint32_t r = 0; r < 1000; r++)
  {
    x = (100 * cos(r));
  }
  stop = micros();
  Serial.print("COS: \t\t");
  Serial.println(stop - start);
  delay(10);

  start = micros();
  for (uint32_t r = 0; r < 1000; r++)
  {
    x = (100 * icos(r));
  }
  stop = micros();
  Serial.print("ICOS: \t\t");
  Serial.println(stop - start);
  delay(10);

  start = micros();
  for (uint32_t r = 0; r < 1000; r++)
  {
    y = (100 * icos256(r)) >> 8;
  }
  stop = micros();
  Serial.print("ICOS256: \t");
  Serial.println(stop - start);
  delay(10);

  for (uint32_t r = 0; r < 1440; r++)
  {
    x = (100 * icos(r));
    y = (100 * icos256(r)) >> 8;
    Serial.print(r);
    Serial.print('\t');
    Serial.print(x);
    Serial.print('\t');
    Serial.print(float(y));
    Serial.println();
  }
}

void loop()
{
}
// -- END OF FILE --
```

Output
```
COS: 		131012
ICOS: 		74928
ICOS256: 	31704
```

so substantial faster but lost accuracy  - diff > 1

**Comment by RobTillaart** [comment]
Printing only the ones with diff > 1 comparing with cos().  => 19 out of 360

code patch
```cpp
  for (uint32_t r = 0; r <= 360; r++)
  {
    x = (100 * cos(r * PI / 180.0));
    y = (100 * icos256(r)) >> 8;
    if (abs(x - y) >= 1)
    {
      Serial.print(r);
      Serial.print('\t');
      Serial.print(x);
      Serial.print('\t');
      Serial.print(float(y));
      Serial.println();
    }
```
output
```
0	100.00	99.00
8	99.03	98.00
14	97.03	96.00
18	95.11	94.00
23	92.05	91.00
47	68.20	67.00
70	34.20	33.00
73	29.24	28.00
76	24.19	23.00
79	19.08	18.00
281	19.08	18.00
284	24.19	23.00
287	29.24	28.00
290	34.20	33.00
313	68.20	67.00
337	92.05	91.00
342	95.11	94.00
346	97.03	96.00
352	99.03	98.00
360	100.00	99.00
```

**Comment by RobTillaart** [comment]
ICOS: 		74928
ICOS256: 	31704

so factor ~2.3 faster seems to be feasible.

Note: probably the tables can be optimized a bit to reduce the errors

**Comment by shaneapowell** [comment]
Interesting!!  Let me see if I can roll your idea in, and see if I can measure the speed difference.

**Comment by shaneapowell** [comment]
Here's the results of trying your `icos256` and `isin256` compared to your standard `icos` and `isin` in my code.
The "render" phase of the graphics output, draws each pixel to a buffer, and for each step in the rotation.
On my smaller clock, I have 25 pixels, and 300 rotation steps.  7500 entries to calculate.  Each of those entries will use `icos` and `isin` once.  It took an average of 222ms to render a full page each frame.  When switching to your `256` variants, it took an average of 208ms per frame.  A savings of about  14ms per frame.  Not an enormous savings, but every clock tick counts when I ramp up the RPMs to 1000.

That was all at 550rpm.

When I cranked it up to 1000rpm. The render phase with the old `icos/isin` took an average of 230ms.  This likely due to the fact that the `render` and `ouput` threads are all pinned to the same 2nd cpu on my esp32.  Meaning, the render phase (which has a lower priority) has to wait for the output phase more often.  With your `icos256/isin256` code @1000rpm, the render phase took an average of 213ms. A savings of about 17ms.

IMO.. worth it.  The less I have to convert to and from float, and the less 'float` math I have to do, the better.  The esp32 does have a basic FPU on it, but it's not really powerful. 

These timings were measured on my oscilloscope with an output pin and it's `Period` function.

**Comment by RobTillaart** [comment]
Thanks for this feedback.
You might gain another us when you use the 8 bit table in isin256() instead of the 16 bit. It would remove the shift 8.

Questions
Do you call the isin() with the same parameter multiple times in a row? If so caching the last value can be interesting.

Do you only use 0..360 degrees?
If so the modulo test can be removed.

Do you call isin and icos with the same angle?
If so merging the calls might be interesting.

**Comment by RobTillaart** [comment]
@shaneapowell

merged the lookup, for if you need both sin() and cos()

.cpp
```cpp
void isincos256(uint32_t v, int &si, int &co)
{
  bool sneg = false;
  bool cneg = false;

  long whole = v;

  if (whole >= 360) 
  {
    whole %= 360;
  }

  int y = whole;  //  16 bit math is faster than 32 bit

  if (y >= 180)
  {
    y -= 180;
    sneg = !sneg;
    cneg = !cneg;
  }

  if (y >= 90)
  {
    y = 180 - y;
    cneg = !cneg;
  }

  si = sinTable16[y] >> 8;
  co = sinTable16[90-y] >> 8;
  if (sneg) si = -si;
  if (cneg) co = -co;
}
```

.h
```cpp
//  calculate both in one call.
void isincos256(uint32_t v, int &si, int &co);
```

On my ESP32 and UNO  there was a serious improvement when you need both
These functions will definitely be in a next release.

Now I'm going to try to roll it into the ```float isin(float)``` which will give some interpolation "challenges"

**Comment by RobTillaart** [comment]
how to call
```cpp
    int p, q;
    isincos256(r, p, q);
    sum += p + q;
```

**Comment by RobTillaart** [comment]
float version
```cpp
void isincos(float f, float &si, float &co)
{
  bool sneg = (f < 0);
  bool cneg = false;
  if (sneg)
  {
    f = -f;
  }

  long whole = f;
  uint8_t remain = (f - whole) * 256;

  if (whole >= 360) 
  {
    whole %= 360;
    //  possible faster for 360-720
    //  if (whole >= 720) whole %= 360;
    //  else whole -= 360;
  }

  int y = whole;  //  16 bit math is faster than 32 bit

  if (y >= 180)
  {
    y -= 180;
    sneg = !sneg;
    cneg = !cneg;
  }

  if (y >= 90)
  {
    y = 180 - y;
    if (remain != 0)
    {
      remain = 255 - remain;
      y--;
    }
    cneg = !cneg;
  }

  //  float value  improves ~4% on avg error  for ~60 bytes.
  uint16_t value = sinTable16[y];
  
  //  interpolate if needed
  if (remain > 0) 
  {
    value = value + ((sinTable16[y + 1] - value) / 8 * remain) / 32;   //  == * remain / 256
  }
  si = value * 0.0000152590219;  //  = / 65535.0
  if (sneg) si = -si;

  value = sinTable16[90-y];
  if (remain > 0) 
  {
    remain = 256 - remain;
    value = value + ((sinTable16[y - 1] - value) / 8 * remain) / 32;   //  == * remain / 256
  }
  co = value * 0.0000152590219;  //  = / 65535.0
  if (cneg) co = -co;
}
```
think there is a bit room for optimizing the remainder part.

**Comment by RobTillaart** [comment]
version 2 with correct remainder handling
```cpp
void isincos(float f, float &si, float &co)
{
  bool sneg = (f < 0);
  bool cneg = false;
  if (sneg)
  {
    f = -f;
  }

  long whole = f;
  uint8_t remain = (f - whole) * 256;

  if (whole >= 360) 
  {
    whole %= 360;
    //  possible faster for 360-720
    //  if (whole >= 720) whole %= 360;
    //  else whole -= 360;
  }

  int y = whole;  //  16 bit math is faster than 32 bit

  if (y >= 180)
  {
    y -= 180;
    sneg = !sneg;
    cneg = !cneg;
  }

  if (y >= 90)
  {
    y = 180 - y;
    if (remain != 0)
    {
      remain = 255 - remain;
      y--;
    }
    cneg = !cneg;
  }

  //  float value  improves ~4% on avg error  for ~60 bytes.
  //  SIN
  uint16_t value = sinTable16[y];
  //  interpolate if needed
  if (remain > 0) 
  {
    value = value + ((sinTable16[y + 1] - value) / 8 * remain) / 32;  //  == * remain / 256
  }
  si = value * 0.0000152590219;  //  = / 65535.0
  if (sneg) si = -si;

  //  COS
  value = sinTable16[90-y];
  if (remain > 0)
  {
    value = sinTable16[89-y];
    remain = 256 - remain;
    value = value + ((sinTable16[90-y] - value) / 8 * remain) / 32;  //  == * remain / 256
  }
  co = value * 0.0000152590219;  //  = / 65535.0
  if (cneg) co = -co;
}
```

The value for cos just differs a bit compared to calling icos() due to rounding I assume but it is in the 4th decimal 
Will investigate that further.

Think I can start working on a PR today.

**Comment by shaneapowell** [comment]
> Questions Do you call the isin() with the same parameter multiple times in a row? If so caching the last value can beinteresting.

Ok.. yeah. that's a smart idea. I'm, doing a loop starting with the pixels, instead of the angle.  so, I'm re-calcing the same angle many times. That's an easy optimization I'll do. Thanks for that.

> 
> Do you only use 0..360 degrees? If so the modulo test can be removed.

I'm currently doing only 0-90 actually, as I'm breaking up the image into it's quadrants and doing a pixel rotation. But, in the future, I can see me doing 0-360.  That said, in my code, I'll never pass a negative, nor over 360. But.. your call on what to do with your modulo check.

> 
> Do you call isin and icos with the same angle? If so merging the calls might be interesting.

Another smart optimization.  I am in fact calling isin and icos right after each other.  A single call to get them both at the same time would be another speed improvement for my code.

Cheers

**Comment by RobTillaart** [comment]
>  I'm re-calcing the same angle many times. That's an easy optimization I'll do. Thanks for that.

As always interested in the gain you make.

**Comment by RobTillaart** [comment]
Found a minor bug in the rounding of the isin() function. 
It is rather small and therefore hard to find. 
Will be fixed in the upcoming PR which will be version 0.3.0 as there is a lot of new functionality.

**Comment by RobTillaart** [comment]
@shaneapowell 
Created develop branch and a PR, see https://github.com/RobTillaart/FastTrig/pull/23

Merging will be later coming week, although it looks pretty stable I want to investigate the details.

But feel free to test them.

**Comment by RobTillaart** [comment]
@shaneapowell 
Merged the integer sin /cos and sincos so they are regular now.

I'm still not happy with the performance/accuracy of **hypot()** - https://github.com/RobTillaart/FastTrig/issues/22
so that needs more investigation and might be included in a later version.

**Pull request merged**
